### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by SergeyGridin** [cameronfarina/airbyob#1]
- [x] Fix formatting on the Sample State

- [x] Add `created_at` and `updated_at` columns to your tables

- [x] Add indices to your tables (should specify this as a bulleted list under each table)

- [x]  Add headers to your Schema

- [x] Add a project

**Comment by cameronfarina** [comment]
should be all set, thanks sergey!

**Comment by cameronfarina** [comment]
opened back up so that you could check and close when you felt it was ready -- sorry for jumping the gun
