### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by cameronfarina** [cameronfarina/airbyob#2]
User Auth is responsible for many things, but mainly for ensuring that users can log in / out safely without having their passwords stored in our database. 

We start by ensuring each user, upon registering, has a session token which is automatically generated. This allows us to create a new session for each user that logs in or signs up on our site.

We then have the ability to log out those users by destroying their session.

At its core, user auth is responsible for:

1. creating sessions
2. logging in users
3. destroy sessions / logging out users

**Comment by SergeyGridin** [comment]
- fix multiple logout buttons in the dropdown.
- consider using icon for a dropdown.
- errors should not persist when navigating from login to signup and vice versa
